name: afercon_pay
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Using a coherent set of Firebase plugins (Updated to latest versions)
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  cloud_functions: any
  firebase_storage: any
  firebase_messaging: any
  firebase_analytics: any
  firebase_crashlytics: any

  # Other dependencies
  cupertino_icons: any
  share_plus: any
  flutter_secure_storage: any
  local_auth: any
  provider: any
  image_picker: any
  mobile_scanner: any
  brasil_fields: any
  url_launcher: any
  flutter_screenutil: any
  intl: any
  shared_preferences: any
  rxdart: any
  timeago: any
  pinput: any
  qr_flutter: any
  screenshot: any
  app_links: any
  google_fonts: any
  pdf: any
  printing: any
  shimmer: any
  permission_handler: any
  flutter_local_notifications: any
  flutter_rating_bar: any
  currency_picker: any
  flutter_form_builder: any
  form_builder_validators: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  mockito: any
  build_runner: any
  flutter_launcher_icons: any

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
